import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";



export default function Home() {
    return (
      
      <div className={styles.container}>
      <nav className={styles.nav}>
      <img src="/homi.png"></img>
        <ul>
          <li>
            <a href="/">
              Home
            </a>
          </li>
          <li>
            <a href="/about">
              About
            </a>
          </li>
        </ul>
      </nav>
        <Head>
          <title>About Homi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/homi.png" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>About Homi</h1>
            <p>At HOMI we believe there is a better way to do real estate. Whether you are a landlord, a tenant, or a prospective buyer, HOMI offers all the benefits of a world-class real estate service at a fraction of the cost, while keeping you informed throughout the entire process. Our technology allows you to calculate the value of your property, create professional marketing content, arrange viewings, collect feedback and process offers quickly and efficiently. Our aim is to make real estate transactions simple and transparent.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam vitae amet mollitia, a molestiae temporibus. Quidem corporis impedit placeat autem blanditiis totam sequi earum iste a dolore voluptatum rerum, aperiam ea tenetur ducimus. Earum, velit. Vero provident, odit fugit architecto mollitia praesentium ullam, voluptate sed eius ab nisi quis eaque earum. Dicta et cum veritatis ad consequatur quam consequuntur praesentium esse aliquam rem repudiandae inventore amet debitis recusandae eveniet facilis, nihil est ullam nobis vitae in, ipsum aliquid. Nobis porro, nihil aspernatur nesciunt autem assumenda aperiam exercitationem ab dolore architecto doloremque aliquid quaerat hic numquam ad quas vel. In, consequatur praesentium velit delectus culpa repudiandae dolor quas illum voluptate sequi eius, inventore eum similique, ea natus at. Atque aliquam nemo, in aspernatur dolorem non cum dolore? Temporibus, sequi inventore provident excepturi sapiente unde aliquam doloribus aut possimus quis ex, vitae consequuntur, quod labore totam maiores consectetur quia deleniti velit! Modi quidem enim suscipit ipsa error sed eum. Nisi voluptatem omnis maxime corporis sequi tempore quos labore voluptas, quo nesciunt eaque sapiente ducimus sit reiciendis ullam quis ipsum, voluptates illum perspiciatis, deleniti assumenda. Deleniti recusandae quibusdam quasi rerum! Veniam, dicta officia aut eum, perferendis blanditiis rem iure distinctio, amet molestiae deleniti iste! Eius expedita optio atque hic porro beatae adipisci incidunt explicabo, quam quaerat doloribus! Aperiam possimus at, in sint nisi sequi earum distinctio debitis asperiores dolor modi odio, suscipit natus, recusandae ipsam! Nesciunt sit id officiis aliquam voluptatibus dignissimos commodi hic quisquam reprehenderit voluptates, quidem dolores, fugiat repudiandae delectus rem illum. Consequatur repudiandae doloribus mollitia temporibus, possimus magni eos vero accusamus nostrum, enim veritatis fuga minus dolorem quod tempore. Alias, unde enim in dolores provident qui maiores repudiandae consequuntur, voluptate necessitatibus architecto odit recusandae possimus? Exercitationem, enim similique provident sint alias unde? Minima maiores dolores repudiandae id laborum sunt voluptate, eaque officia in iste, possimus ipsa quisquam cum illo tempora nobis, magnam consectetur porro tempore atque corporis. Voluptatum eveniet minima quibusdam? Delectus suscipit omnis vero saepe inventore, ipsa deserunt maiores impedit? Vel cumque ducimus consequuntur dicta minima soluta. Nostrum repellat odit est corporis fugit. Iste modi ex ut error culpa praesentium omnis accusantium veritatis minima aut eligendi ducimus maiores fugiat aliquid inventore vel esse, perspiciatis, dicta, voluptas atque dolor commodi? Itaque dolore voluptatem fugiat dicta fugit nam animi! Optio iusto adipisci perspiciatis. Qui soluta sapiente vitae expedita et unde doloremque eos, beatae, voluptatem rem cumque molestiae assumenda nihil ratione eligendi necessitatibus laudantium est? Laudantium repellat odit quae laborum culpa hic optio minima voluptates ut exercitationem, aliquid dolorem sequi sit molestias, doloribus obcaecati delectus autem atque neque doloremque quidem, ea quas qui fugiat! Eveniet possimus obcaecati impedit expedita sit beatae cum totam praesentium, minus explicabo id et delectus odit itaque exercitationem hic. Doloribus, necessitatibus sapiente perferendis amet iure fugiat eligendi similique deleniti laborum hic ducimus aut enim mollitia illo eaque nihil, soluta quos commodi architecto dolore magnam! Iusto nemo nisi ex consequatur repellat, cumque in numquam consectetur rerum autem. Vel deleniti at assumenda magnam quo quam, libero dignissimos quis culpa doloribus.
            Atque aliquam nemo, in aspernatur dolorem non cum dolore? Temporibus, sequi inventore provident excepturi sapiente unde aliquam doloribus aut possimus quis ex, vitae consequuntur, quod labore totam maiores consectetur quia deleniti velit! Modi quidem enim suscipit ipsa error sed eum. Nisi voluptatem omnis maxime corporis sequi tempore quos labore voluptas, quo nesciunt eaque sapiente ducimus sit reiciendis ullam quis ipsum, voluptates illum perspiciatis, deleniti assumenda. Deleniti recusandae quibusdam quasi rerum! Veniam, dicta officia aut eum, perferendis blanditiis rem iure distinctio, amet molestiae deleniti iste! Eius expedita optio atque hic porro beatae adipisci incidunt explicabo, quam quaerat doloribus! Aperiam possimus at, in sint nisi sequi earum distinctio debitis asperiores dolor modi odio, suscipit natus, recusandae ipsam! Nesciunt sit id officiis aliquam voluptatibus dignissimos commodi hic quisquam reprehenderit voluptates, quidem dolores, fugiat repudiandae delectus rem illum. Consequatur repudiandae doloribus mollitia temporibus, possimus magni eos vero accusamus nostrum, enim veritatis fuga minus dolorem quod tempore. Alias, unde enim in dolores provident qui maiores repudiandae consequuntur, voluptate necessitatibus architecto odit recusandae possimus? Exercitationem, enim similique provident sint alias unde? Minima maiores dolores repudiandae id laborum sunt voluptate, eaque officia in iste, possimus ipsa quisquam cum illo tempora nobis, magnam consectetur porro tempore atque corporis. Voluptatum eveniet minima quibusdam? Delectus suscipit omnis vero saepe inventore, ipsa deserunt maiores impedit? Vel cumque ducimus consequuntur dicta minima soluta. Nostrum repellat odit est corporis fugit. Iste modi ex ut error culpa praesentium omnis accusantium veritatis minima aut eligendi ducimus maiores fugiat aliquid inventore vel esse, perspiciatis, dicta, voluptas atque dolor commodi? Itaque dolore voluptatem fugiat dicta fugit nam animi! Optio iusto adipisci perspiciatis. Qui soluta sapiente vitae expedita et unde doloremque eos, beatae, voluptatem rem cumque molestiae assumenda nihil ratione eligendi necessitatibus laudantium est? Laudantium repellat odit quae laborum culpa hic optio minima voluptates ut exercitationem, aliquid dolorem sequi sit molestias, doloribus obcaecati delectus autem atque neque doloremque quidem, ea quas qui fugiat! Eveniet possimus obcaecati impedit expedita sit beatae cum totam praesentium, minus explicabo id et delectus odit itaque exercitationem hic. Doloribus, necessitatibus sapiente perferendis amet iure fugiat eligendi similique deleniti laborum hic ducimus aut enim mollitia illo eaque nihil, soluta quos commodi architecto dolore magnam! Iusto nemo nisi ex consequatur repellat, cumque in numquam consectetur rerum autem. Vel deleniti at assumenda magnam quo quam, libero dignissimos quis culpa doloribus.

</p> 

          
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
         HOMI 2022 &copy;
          <span className={styles.logo}>
            <Image src="/HOMILOGO.png" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}