import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import data from "../utils/data.json";



export default function Home() {
  return (
    
    <div className={styles.container}>
    <nav className={styles.nav}>
    <img src="/homi.png"></img>
      <ul>
        <li>
          <a href="/">
            Home
          </a>
        </li>
        <li>
          <a href="/about">
            About
          </a>
        </li>
      </ul>
    </nav>
      <Head>
        <title>Homi Listings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/homi.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Public Listings</h1>

    

        <div id="cards" className={styles.grid}>
          {/* This is the the function that loads all the data from the JSON file . I choose to display them in card form */}
          {/* However for some reason the changes on the .card class do not take so I used inline CSS to modify their appearance */}
          {data.forEach((element) => {
            useEffect(() => {
              document.getElementById(
                "cards"
              ).innerHTML += `<div className= ${styles.card} style="background-color:rgb(97, 124, 224);margin:20px ; text-align:left ; border:2px solid whitesmoke; border-radius:10px;"><img src=${element.media} width="250" height ="200"><p style="margin:0;font-size:1.25rem;line-height:1.5rem" >Type  : ${element.property_subcategory}</p> <p style="margin:0;font-size:1.25rem;line-height:1.5rem">Listing Type : ${element.list_type}</p> <p style="margin:0;font-size:1.25rem;line-height:1.5rem">Size : ${element.size}</p> <p style="margin:0;font-size:1.25rem;line-height:1.5rem">Price : ${element.price}</p></div>`;
            });
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
         HOMI 2022 &copy;
          <span className={styles.logo}>
            <Image src="/HOMILOGO.png" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
